# Generated by Django 5.2 on 2025-06-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_alter_studentinfo_std_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subject_name',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='teacher_username',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
