# Generated by Django 5.2 on 2025-06-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_result_teach_username_alter_test_test_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='valid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('sub_name', models.CharField(max_length=255)),
                ('PRN', models.CharField(default=0, max_length=225)),
                ('valid', models.IntegerField(default=0)),
                ('test_created_at', models.DateTimeField(auto_now_add=True)),
                ('test_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
