# Generated by Django 5.2 on 2025-06-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='valid',
            name='code',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
